apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: banking-system
spec:
  selector:
    app: banking-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
