name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: golang:1.23

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Confirm Go version
      run: go version
      
    - name: Install golang-migrate
      run: |
        apt-get update
        apt-get install -y curl tar postgresql-client
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz -o migrate.tar.gz
        tar -xvzf migrate.tar.gz
        mv migrate /usr/local/bin/
        which migrate

    - name: Wait for Postgres to be ready
      run: |
        for i in {1..10}; do
        pg_isready -h postgres -p 5432 && break
        echo "Waiting for Postgres... ($i)"
        sleep 5
        done

    - name: run server
      env:
          DB_USER: user
          DB_PASSWORD: admin
          DB_NAME: simple_bank
      run: go run cmd/main.go

    - name: Run migrations
      run: make migrateup
      working-directory: /__w/BankingSystem/BankingSystem

    - name: Run tests 
      run: make test
      working-directory: /__w/BankingSystem/BankingSystem

